### ISSUE TITLE
TargetFrameworkVersion

### ISSUE THREAD

**Issue by pszentiv** [esimiele/SimpleProgressWindow#1]
Hi,

Is it possible to change the TargetFrameworkVersion from 4.7.2 to 4.5.2? With the change the NuGet package can be used from 15.6 ESAPI version.

Regards,
Peter

**Comment by esimiele** [comment]
Hey Peter,

I wrote the code to use 4.7.2 to ensure it could be used for both v15.6 and v16.1 of Eclipse. I currently use the nuget package (with 4.7.2) in my vmat tbi and vmat csi autoplanning code (https://github.com/esimiele/VMAT-TBI-CSI), which was developed on v15.6 of Eclipse. If you use the nuget package, just make sure the .net framework version used in all projects that reference it is 4.7.2, otherwise it visual studio will throw errors. Otherwise, feel free to clone this repo, manually include it in your project, and change the .net framework version (this repo should be the same as the nuget package). 

Let me know if that fixes it.
Thanks!
Eric

**Comment by esimiele** [comment]
Since I haven't heard from you, I'm assuming you were able to resolve the issue. If not, feel free to shoot me a message and I'll re-open this issue.
